# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

#pipelines > steps > jobs

stages:
- stage: Build
  jobs:
  - job: firstjob
    steps: 
    - bash: echo first job and build
- stage: DevDeploy
  dependsOn: QADeploy

  jobs:
    - job: secondjob
      steps:
      - bash: echo 'second job and dev' 
- stage: QADeploy

  jobs:
    - job: Thirdjob
      steps: 
      - bash: echo third job and QA
- stage: ProdDeploy
  dependsOn: 
  - Build
  - QADeploy
  jobs:
    - job: fourthjob
      steps: 
      - bash: echo fourth job and prod
- stage: Gabbar
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
    - job: fifthjob
      steps: 
      - bash: echo fifth job and gabbar
  